-- 1- Explore the Database
SELECT 
* 
FROM INFORMATION_SCHEMA.TABLES;

--  Retrieve all columns for a specific table (dim_customers)
SELECT 
*
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

-- 2- Dimensions Exploration

-- Retrieve a list of unique countries
SELECT DISTINCT 
    country 
FROM gold.dim_customers
ORDER BY country;

-- Retrieve a list of unique categories, subcategories, and products
SELECT DISTINCT 
    category, 
    subcategory, 
    product_name 
FROM gold.dim_products
ORDER BY category, subcategory, product_name;

-- 3- Date Exploration

-- Determine the first and last order date and the total duration in months
SELECT 
    MIN(order_date) AS first_order_date,
    MAX(order_date) AS last_order_date,
    DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS order_range_months
FROM gold.fact_sales;

-- Find the youngest and oldest customer based on birthdate
SELECT
    MIN(birthdate) AS oldest_birthdate,
    DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS oldest_age,
    MAX(birthdate) AS youngest_birthdate,
    DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers;

-- 4- Measures Exploration

-- Find The Total Sales
SELECT 
SUM(sales_amount) AS total_sales
FROM gold.fact_sales;

-- Find How Many Items are Sold
SELECT 
SUM(quantity) AS total_quantity
FROM gold.fact_sales;

-- Find the Average selling price 
SELECT 
AVG(price) AS average_price
FROM gold.fact_sales;

-- Find the total number of orders
SELECT 
COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales;

-- Find the Total number of products
SELECT 
COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products;

-- Find the Total number of customers
SELECT 
COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers;

-- Find the Total number of customers that has placed an order
SELECT 
COUNT(DISTINCT customer_key) AS total_customers_ordered
FROM gold.fact_sales;

-- Generate a report that shows all key metrics
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL 
SELECT 'Total Orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Products' AS measure_name, COUNT(DISTINCT product_key) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total Customers' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total Customers Ordered' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales;

-----------------

-- 5- Magnitude Analysis
-- Find total customers by countries
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Average cost in each category
SELECT
category,
AVG(product_cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- Total Revenue generated for each category
SELECT
p.category,
SUM(f.sales_amount) AS total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY category 
ORDER BY total_sales DESC;

-- Total Revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_sales DESC;

-- Distiribution of sold items across countries 
SELECT
c.country,
SUM(f.quantity) AS total_quantity
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC;

-- 6- Ranking
-- Which 5 Products generates the highest revenue

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- What are the worst 5 products in revenue

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue;

-- Top 10 customers generating revenue (Windows Functions)
SELECT * FROM (
    SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revnue,
    ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS sales_rank
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
    GROUP BY c.customer_key, c.first_name, c.last_name) t
WHERE sales_rank <= 10
